=== vincedgy/NetBeans_JSF_plus_dojo/src/main/java/com/vincedgy/jsf2project/exercice10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://jad.orsys.fr/exercice10" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://jad.orsys.fr/exercice10">

    <complexType name="ville">
    	<attribute name="nom" type="string"></attribute>
    	<attribute name="codePostal" type="int"></attribute>
    </complexType>

    <complexType name="mode-de-transport">
    	<attribute name="nom" type="string"></attribute>
    	<attribute name="identifiant" type="int"></attribute>
    </complexType>

    <element name="agence-voyages">
    	<complexType>
    		<sequence>
    			<element name="ville" type="tns:ville"
    				maxOccurs="unbounded" minOccurs="0">
    			</element>
    			<element name="mode-de-Transport" type="tns:mode-de-transport" maxOccurs="unbounded" minOccurs="0"></element>
    		</sequence>
    	</complexType>
    </element>
</schema>

=== vincedgy/NetBeans_JSF_plus_dojo/src/main/java/com/vincedgy/jsf2project/exercice10.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:agence-voyages xmlns:tns="http://jad.orsys.fr/exercice10"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jad.orsys.fr/exercice10 exercice10.xsd ">
	<tns:ville codePostal="80021" nom="Amiens" />
	<tns:ville codePostal="25056" nom="Besancon"/>
	<tns:ville codePostal="14118" nom="Caen"/>
	<tns:ville codePostal="21231" nom="Dijon"/>
	<tns:ville codePostal="91226" nom="Etrechy"/>
	<tns:ville codePostal="35115" nom="Fougere"/>
	<tns:ville codePostal="38185" nom="Grenoble"/>
	<tns:mode-de-Transport identifiant="1" nom="Voiture" />
	<tns:mode-de-Transport identifiant="2" nom="Avion"/>
	<tns:mode-de-Transport identifiant="3" nom="Train"/>
</tns:agence-voyages>
