=== vincedgy/NetBeans_JSF_plus_dojo/src/main/java/com/vincedgy/jsf2project/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/schema"
	xmlns:tns="http://www.example.org/schema" elementFormDefault="qualified">
	
	<complexType name="ville">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="nom" type="string"></element>
			<element name="code-postal" type="string"></element>
		</sequence>
	</complexType>
	
    <complexType name="modes">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="mode" type="string"></element>
		</sequence>
	</complexType>

	<complexType name="trajet">
		<sequence>
			<element name="ville" type="tns:ville" minOccurs="1" maxOccurs="1"></element>
			<element name="modes" type="tns:modes" minOccurs="1" maxOccurs="unbounded"></element>								
		</sequence>
	</complexType>
	
	<complexType name="voyage">
		<sequence id="trajets" minOccurs="0" maxOccurs="unbounded">
			<element name="trajet" type="tns:trajet"></element>			
		</sequence>
	</complexType>

    <element name="AgenceVoyages" type="tns:voyage"></element>
</schema>

=== vincedgy/NetBeans_JSF_plus_dojo/src/main/java/com/vincedgy/jsf2project/schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:AgenceVoyages xmlns:tns="http://www.example.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/schema schema.xsd ">
  <tns:trajet>
    <tns:ville>
      <tns:nom>Paris</tns:nom>
      <tns:code-postal>75000</tns:code-postal>
    </tns:ville>
    <tns:modes>
      <tns:mode>Voiture</tns:mode>
      <tns:mode>Train</tns:mode>
      <tns:mode>Avion</tns:mode>
    </tns:modes>
  </tns:trajet>
  
  <tns:trajet>
    <tns:ville>
      <tns:nom>Foug√®res</tns:nom>
      <tns:code-postal>35115</tns:code-postal>
    </tns:ville>
    <tns:modes>
      <tns:mode>Voiture</tns:mode>
      <tns:mode>Train</tns:mode>
    </tns:modes>
  </tns:trajet>
  
  <tns:trajet>
    <tns:ville>
      <tns:nom>Caen</tns:nom>
      <tns:code-postal>14118</tns:code-postal>
    </tns:ville>
    <tns:modes>
      <tns:mode>Voiture</tns:mode>
      <tns:mode>Train</tns:mode>
    </tns:modes>
  </tns:trajet>
  
</tns:AgenceVoyages>
